### ISSUE TITLE
XHTML Error on many pages

### ISSUE THREAD

**Issue by goombado** [thsconline/s#1]
On the Year 12 page, within many of the Subject Folders, the page attempts to load and then shows 

`XHTML Error. Unable to load this page correctly: Exception: Error on line 5: Open quote is expected for attribute "name" associated with an element type "meta".`

at the top of the page, with nothing else. Just wanted to bring this issue to the foreground in case anybody else has been affected by it.

Thanks, goombado

**Comment by thsconline** [comment]
This is probably because the page is a HTML page not XHTML page. I used to have an error handling that would still spit out the HTML but that code got removed for some reason when I put the site back up.

**Comment by thsconline** [comment]
This is not a Github issue and has been fixed by the rewriting the relevant google app scripts.
